package Utils;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXTextField;
import com.jfoenix.validation.RequiredFieldValidator;
import com.jfoenix.validation.base.ValidatorBase;
import javafx.beans.Observable;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.scene.control.TextInputControl;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

import static javafx.beans.binding.Bindings.createBooleanBinding;

public class Helper {

    private static Random GENERATOR = new Random();
    private static SimpleDateFormat SIMPLE_DATE_FORMASTTER =  new SimpleDateFormat("dd.MM.yyyy");
    public static final long NUMBER_OF_MILLISECONDS_IN_DAY = 86400000L;
    public static final String EMPTY_WARNING_MESSAGE = "Vstup musí byť zadaný";
    public static final String EMPTY_WARNING_MESSAGE_NUMBER = "Vstup musí byť celé číslo";


    private Helper() {}

    public static String GetNahodnyString(int dlzka) {
        String abeceda = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        StringBuilder string = new StringBuilder();
        while (string.length() < 16) { // length of the random string.
            int index = (int) (GENERATOR.nextFloat() * abeceda.length());
            string.append(abeceda.charAt(index));
        }
        return string.toString();
    }

    public static long ConvertLocalDateToLong(LocalDate date) {
        return date.toEpochDay() * NUMBER_OF_MILLISECONDS_IN_DAY;
    }

    // generuje cislo v rozsahy 0 az max - 1
    public static int GetNahodneCislo(int max) {
        int generated = GENERATOR.nextInt(max);
        return generated;
    }

    public static String GetNahodneRodneCislo() {
        return GetNahodnyString(16);
    }

    public static String GetNahodnyNazovKatastralnehoUzemie() {
        return KATASTRALNE_UZEMIA.get(GetNahodneCislo(KATASTRALNE_UZEMIA.size() - 1));
    }

    public static String GetNahodneMenoAPriezvisko() {
        return  MENA.get(GetNahodneCislo(MENA.size() - 1)) + " " + PRIEZVISKA.get(GetNahodneCislo(PRIEZVISKA.size() - 1));
    }

    public static long GetNahodnyDatumNarodenia() {
        return ((long)(GENERATOR.nextDouble()*(1262304000000L)));
    }

    public static String FormatujDatum(long date) {
        return SIMPLE_DATE_FORMASTTER.format(date);
    }


    public static void decorateTextFieldWithValidator(JFXTextField textField, SimpleBooleanProperty propertyToBind) {
        textField.getValidators().add(new RequiredFieldValidator() {
            {
                setMessage(EMPTY_WARNING_MESSAGE);
            }
        });
        textField.textProperty().addListener((observable, oldValue, newValue) -> {
            boolean validateResult = textField.validate();
            propertyToBind.set(validateResult);
        });
    }

    public static void decorateTextFieldWithValidator(JFXTextField textField, SimpleBooleanProperty propertyToBind, int maximumlength, String atributeName) {
        textField.getValidators().addAll(new RequiredFieldValidator() {
            {
                setMessage(EMPTY_WARNING_MESSAGE);
            }
        }, new ValidatorBase() {
            @Override
            protected void eval() {
                TextInputControl textField = (TextInputControl)this.srcControl.get();
                String text = textField.getText();
                if (text != null && text.length() > 0)
                {
                    if (text.contains(" ")) {
                        this.hasErrors.set(true);
                        setMessage(atributeName +" nesmie mať medzery");
                        return;
                    }
                    if (text.length() == maximumlength) {
                        this.hasErrors.set(false);
                    } else {
                        setMessage(atributeName +" musí mať 16 znakov");
                        this.hasErrors.set(true);
                    }

                } else
                {
                    this.hasErrors.set(false);
                }
            }
        });
        textField.textProperty().addListener((observable, oldValue, newValue) -> {
            if (textField.getText().length() > maximumlength) {
                String s = textField.getText().substring(0, maximumlength);
                textField.setText(s);
            }
            boolean validateResult = textField.validate();
            propertyToBind.set(validateResult);
        });
    }

    public static void decorateNumberTextFieldWithValidator(JFXTextField textField, SimpleBooleanProperty propertyToBind) {
        textField.getValidators().addAll(new RequiredFieldValidator() {
            {
                setMessage(EMPTY_WARNING_MESSAGE);
            }
        }, new ValidatorBase() {
            {
                setMessage(EMPTY_WARNING_MESSAGE_NUMBER);
            }
            @Override
            protected void eval() {
                TextInputControl textField = (TextInputControl)this.srcControl.get();
                String text = textField.getText();
                try {
                    this.hasErrors.set(false);
                    if (!text.isEmpty()) {
                        Long.parseLong(text);
                    }
                } catch (Exception var4) {
                    this.hasErrors.set(true);
                }
            }
        });

        textField.textProperty().addListener((observable, oldValue, newValue) -> {
            if (!newValue.matches("\\d*")) {
                textField.setText(newValue.replaceAll("[^\\d]", ""));
            }
            boolean validateResult = textField.validate();
            propertyToBind.set(validateResult);
        });

    }

    public static boolean disableButton(JFXButton button, List<SimpleBooleanProperty> simpleBooleanProperties, Runnable validationCheck) {
        if (button.isDisable() == false && simpleBooleanProperties.stream().anyMatch(simpleBooleanProperty -> simpleBooleanProperty.get() == false)) {
            validationCheck.run();
            button.disableProperty().unbind();
            button.disableProperty().bind( createBooleanBinding(
                    () -> simpleBooleanProperties.stream().anyMatch(simpleBooleanProperty -> simpleBooleanProperty.get() == false),(Observable[]) simpleBooleanProperties.toArray()
            ));
            return true;
        }
        return false;
    }

    private static List<String> MENA = Arrays.asList(
            "Adam",
            "Adrian",
            "Adriana",
            "Agata",
            "Agim",
            "Aichatou",
            "Alek",
            "Alena",
            "Ales",
            "Alexander",
            "Alexandra",
            "Alfred",
            "Alica",
            "Alojz",
            "Alzbeta",
            "Andrea",
            "Andrej",
            "Aneta",
            "Angela",
            "Anna",
            "Anthony",
            "Anton",
            "Antonia",
            "Antonim",
            "Antonin",
            "Antonios",
            "Arpad",
            "Artur",
            "Augustin",
            "Barbara",
            "Barbora",
            "Bastien",
            "Beata",
            "Benedikt",
            "Bibiana",
            "Biljana",
            "Blanka",
            "Blazej",
            "Bohdan",
            "Bohdana",
            "Bohumil",
            "Bohumir",
            "Bohus",
            "Bohuslav",
            "Boleslava",
            "Boris",
            "Bozena",
            "Branislav",
            "Bretislav",
            "Bronislav",
            "Bronislava",
            "Bruno",
            "Chen",
            "Csaba",
            "Ctibor",
            "Cvetelina",
            "Dagmar",
            "Dalibor",
            "Dam",
            "Damjan",
            "Dana",
            "Danes",
            "Danica",
            "Daniel",
            "Daniela",
            "Danka",
            "Darina",
            "Dasa",
            "David",
            "Denisa",
            "Diana",
            "Dimo",
            "Dmitrij",
            "Dominik",
            "Dominika",
            "Dragomir",
            "Drahomira",
            "Drahoslav",
            "Du?an",
            "Duc",
            "Dusan",
            "Dusana",
            "Edgar",
            "Edita",
            "Eduard",
            "Edvin",
            "Elemir",
            "Elena",
            "Eleonora",
            "Ema",
            "Emese",
            "Emil",
            "Emilia",
            "Emilian",
            "Erich",
            "Erik",
            "Erika",
            "Ernest",
            "Eugenia",
            "Eva",
            "Fangling",
            "Fedor",
            "Felix",
            "Filip",
            "Flora",
            "Frantisek",
            "Frederic",
            "Fridrich",
            "Gabriel",
            "Gabriela",
            "George",
            "Gertruda",
            "Gregor",
            "Gustav",
            "Hana",
            "Helena",
            "Helmut",
            "Henrich",
            "Henrieta",
            "Hubert",
            "Hynek",
            "Igor",
            "Imrich",
            "Ingrid",
            "Ingrida",
            "Irena",
            "Iva",
            "Ivan",
            "Ivana",
            "Iveta",
            "Ivica",
            "Ivo",
            "Ivona",
            "Jakub",
            "Jan",
            "Jana",
            "Janka",
            "Janusz",
            "Jarkko",
            "Jarmila",
            "Jaromir",
            "Jaroslav",
            "Jaroslava",
            "Jergus",
            "Jilja",
            "Jiri",
            "Jitka",
            "Johanna",
            "Jolana",
            "Josef",
            "Jozef",
            "Jozefina",
            "Julia",
            "Julian",
            "Juliana",
            "Julis",
            "Julius",
            "Jun",
            "Juraj",
            "Kamil",
            "Kamila",
            "Karel",
            "Karin",
            "Karol",
            "Katarina",
            "Katerina",
            "Khaled",
            "Koloman",
            "Konstantin",
            "Kornel",
            "Kristina",
            "Kvetoslav",
            "Ladislav",
            "Ladislava",
            "Laura",
            "Le",
            "Lenka",
            "Leopold",
            "Leos",
            "Lev",
            "Liana",
            "Libor",
            "Libusa",
            "Linda",
            "Livia",
            "Lubica",
            "Lubomir",
            "Lubomira",
            "Lubos",
            "Luboslav",
            "Luboslava",
            "Lucia",
            "Lucian",
            "Ludek",
            "Ludmila",
            "Ludovit",
            "Lujza",
            "Lukas",
            "Lydia",
            "Mael",
            "Magda",
            "Magdalena",
            "Marcel",
            "Marcela",
            "Marek",
            "Margareta",
            "Margita",
            "Maria",
            "Marian",
            "Mariana",
            "Marianna",
            "Marie",
            "Marietta",
            "Marina",
            "Mario",
            "Marius",
            "Marko",
            "Maros",
            "Marta",
            "Martim",
            "Martin",
            "Martina",
            "Matej",
            "Matus",
            "Maxime",
            "Maximilan",
            "Metod",
            "Michael",
            "Michaela",
            "Michal",
            "Mikulas",
            "Milada",
            "Milan",
            "Milena",
            "Milon",
            "Milos",
            "Miloslav",
            "Miluse",
            "Mina",
            "Miriam",
            "Miriama",
            "Mirka",
            "Mirko",
            "Miroslav",
            "Miroslava",
            "Mojmir",
            "Monika",
            "Nada",
            "Nadezda",
            "Naima",
            "Najib",
            "Nguyen",
            "Nikola",
            "Nikolas",
            "Norbert",
            "Oldrich",
            "Oleg",
            "Olga",
            "Oliver",
            "Ondrej",
            "Otakar",
            "Otmar",
            "Oto",
            "Patricia",
            "Patrik",
            "Paulina",
            "Pavel",
            "Pavla",
            "Pavlina",
            "Pavol",
            "Pedro",
            "Peter",
            "Petr",
            "Petra",
            "Petre",
            "Pham",
            "Pierre",
            "Premysl",
            "Radek",
            "Radim",
            "Radka",
            "Radko",
            "Radomir",
            "Radoslav",
            "Radovan",
            "Rashid Kassim",
            "Rastislav",
            "Renata",
            "Rene",
            "Ricardo Antonio",
            "Richard",
            "Robert",
            "Roland",
            "Roman",
            "Ronald",
            "Rostislav",
            "Rozalia",
            "Rudolf",
            "Ryszard",
            "Samuel",
            "Sarka",
            "Sebastian",
            "Silvester",
            "Silvia",
            "Simon",
            "Simona",
            "Slava",
            "Slavek",
            "Slavka",
            "Slavo",
            "Slavomil",
            "Slavomir",
            "Slavomira",
            "Sona",
            "Stanislav",
            "Stanislava",
            "Stefan",
            "Svatopluk",
            "Svetlana",
            "Sylvia",
            "Tarek",
            "Tatiana",
            "Terezia",
            "Thibaut",
            "Tiago",
            "Tibor",
            "Timotej",
            "Tomas",
            "Vaclav",
            "Valer",
            "Valeria",
            "Vanda",
            "Velislava",
            "Vera",
            "Veronika",
            "Veselina",
            "Viera",
            "Viktor",
            "Viktoria",
            "Viktorie",
            "Viliam",
            "Vilos",
            "Viola",
            "Vit",
            "Vladana",
            "Vlademar",
            "Vladimir",
            "Vladimira",
            "Vladislav",
            "Vladislava",
            "Vlasta",
            "Vlastimil",
            "Vojtech",
            "Vratislav",
            "Vratko",
            "Vu",
            "Walter",
            "Wieslaw",
            "Xenia",
            "Xiaodong",
            "Yichen",
            "Yveta",
            "Zaneta",
            "Zbynek",
            "Zdena",
            "Zdenek",
            "Zdenka",
            "Zdenko",
            "Zdeno",
            "Zelislava",
            "Zita",
            "Zlata",
            "Zoltan",
            "Zora",
            "Zoran",
            "Zuzana"
    );

    private static List<String> PRIEZVISKA = Arrays.asList(
            "Abaffy",
            "Abrahamek",
            "Abrosimov",
            "Abu-Rjaiova",
            "Achberger",
            "Acs",
            "Adam",
            "Adamca",
            "Adamcek",
            "Adamcik",
            "Adamec",
            "Adamek",
            "Adamica",
            "Adamikova",
            "Adamko",
            "Adamkova",
            "Adamus",
            "Albert",
            "Alchaaer",
            "Alexik",
            "Alfardan",
            "Allo",
            "Alman",
            "Almanova",
            "Amate",
            "Ambrozi",
            "Ancic",
            "Andel",
            "Andelek",
            "Andilova",
            "Ando",
            "Andrasik",
            "Andraskova",
            "Andreanska",
            "Andreansky",
            "Andrejkovic",
            "Androvic",
            "Andruska",
            "Angelovic",
            "Antal",
            "Antol",
            "Antoniak",
            "Appel",
            "Arendas",
            "Arpas",
            "Augustin",
            "Auxt",
            "Babcan",
            "Babej",
            "Babela",
            "Babelova",
            "Babik",
            "Babin",
            "Babinec",
            "Babis",
            "Babjak",
            "Babjakova",
            "Bablena",
            "Babos",
            "Babuliak",
            "Baca",
            "Bace",
            "Bachar",
            "Bachorik",
            "Bacinsky",
            "Backady",
            "Backo",
            "Bacova",
            "Baculak",
            "Bacur",
            "Badinka",
            "Bado",
            "Badura",
            "Bahna",
            "Bajdich",
            "Bajtos",
            "Bakala",
            "Bakita",
            "Bako",
            "Bakos",
            "Balada",
            "Balak",
            "Balakova",
            "Balas",
            "Balaz",
            "Balazik",
            "Balaziova",
            "Balazsova",
            "Balcarek",
            "Balcarkova",
            "Balec",
            "Balej",
            "Balek",
            "Balgova",
            "Balint",
            "Balko",
            "Balla",
            "Ballesteros",
            "Balsik",
            "Baluch",
            "Balusinska",
            "Balvan",
            "Balvin",
            "Balvon",
            "Banas",
            "Bandos",
            "Bandur",
            "Banouch",
            "Banovec",
            "Barabasova",
            "Baradlai",
            "Baran",
            "Barancik",
            "Barancok",
            "Baranec",
            "Baraniak",
            "Baranova",
            "Barat",
            "Barathova",
            "Barciak",
            "Bardy",
            "Bares",
            "Bariak",
            "Barilla",
            "Barinova",
            "Barkol",
            "Barova",
            "Barta",
            "Bartak",
            "Bartakova",
            "Bartalos",
            "Bartalosova",
            "Bartanus",
            "Bartanusova",
            "Bartek",
            "Bartik",
            "Bartikova",
            "Bartko",
            "Bartl",
            "Bartok",
            "Barton",
            "Bartos",
            "Bartus",
            "Barysz",
            "Barzik",
            "Basarova",
            "Basista",
            "Baska",
            "Batora",
            "Batorova",
            "Batoryova",
            "Batova",
            "Bauer",
            "Bavolar",
            "Bavolova",
            "Bayer",
            "Bazik",
            "Bazo",
            "Bebjakova",
            "Bednar",
            "Bednarik",
            "Bednarova",
            "Bedus",
            "Behan",
            "Behrikova",
            "Behul",
            "Beil",
            "Beke",
            "Belak",
            "Belakova",
            "Belan",
            "Belancova",
            "Belcik",
            "Beles",
            "Beliancin",
            "Beliansky",
            "Belica",
            "Belicka",
            "Belko",
            "Bella",
            "Bellak",
            "Bellovic",
            "Bellus",
            "Bena",
            "Benadik",
            "Benadikova",
            "Bencik",
            "Bencikova",
            "Bencurikova",
            "Bencurova",
            "Bendicek",
            "Bendik",
            "Bendzala",
            "Benech",
            "Benes",
            "Beniac",
            "Beniciak",
            "Benicky",
            "Benikova",
            "Benikovsky",
            "Benko",
            "Benkova",
            "Beno",
            "Benova",
            "Benovic",
            "Benus",
            "Benuska",
            "Beracko",
            "Berak",
            "Beranek",
            "Berdak",
            "Bereznanin",
            "Bereznaninova",
            "Bergerova",
            "Bergmann",
            "Berka",
            "Berkesova",
            "Bernat",
            "Bernatak",
            "Bernatova",
            "Berta",
            "Berthier",
            "Berthoty",
            "Bertoli",
            "Berzak",
            "Berzedy",
            "Beseda",
            "Betinsky",
            "Bezakova",
            "Bezdekova",
            "Biel",
            "Bielcik",
            "Bielek",
            "Bielicka",
            "Bielik",
            "Bielikova",
            "Bieloncik",
            "Biely",
            "Bigda",
            "Bihari",
            "Bilek",
            "Billik",
            "Bily",
            "Bim",
            "Binka",
            "Binkova",
            "Bires",
            "Biros",
            "Bismuth",
            "Bistut",
            "Bitara",
            "Bizik",
            "Bizon",
            "Bizonova",
            "Bjelobrk",
            "Blaho",
            "Blahova",
            "Blahovec",
            "Blahusiak",
            "Blanarova",
            "Blascak",
            "Blascik",
            "Blasko",
            "Blaskova",
            "Blazej",
            "Blazek",
            "Blazekova",
            "Bley",
            "Blizniakova",
            "Bobak",
            "Bobcikova",
            "Bobenic",
            "Bobok",
            "Bobovsky",
            "Bocek",
            "Bocko",
            "Boda",
            "Bodor",
            "Bodorik",
            "Bodova",
            "Bohac",
            "Bohacik",
            "Bohuncak",
            "Bohus",
            "Boixel",
            "Bojkovsky",
            "Bojnicky",
            "Bojsa",
            "Boka",
            "Boldys",
            "Bolek",
            "Bolemant",
            "Bolgac",
            "Bolvansky",
            "Bombara",
            "Bombiak",
            "Borbas",
            "Bordac",
            "Borgula",
            "Borik",
            "Borikova",
            "Borisova",
            "Borko",
            "Borody",
            "Boron",
            "Boros",
            "Borot",
            "Borovicka",
            "Borovsky",
            "Bors",
            "Borsc",
            "Bosakova",
            "Bosansky",
            "Bosiak",
            "Bosik",
            "Bosko",
            "Bosnak",
            "Botka",
            "Botlik",
            "Botyanszky",
            "Bouz",
            "Boxanova",
            "Bozek",
            "Brablec",
            "Brachtl",
            "Bracinik",
            "Bradlerova",
            "Bradnansky",
            "Brandalik",
            "Brandys",
            "Branik",
            "Branka",
            "Brasen",
            "Braska",
            "Brasko",
            "Braskova",
            "Brehovsky",
            "Brejcak",
            "Brejova",
            "Brezani",
            "Brezansky",
            "Breziansky",
            "Brezny",
            "Brezovska",
            "Brida",
            "Brienik",
            "Brieskova",
            "Bris",
            "Britka",
            "Britkova",
            "Britvik",
            "Brna",
            "Brno",
            "Brodnanska",
            "Brodniansky",
            "Brodziansky",
            "Brojo",
            "Brokes",
            "Broncek",
            "Broncekova",
            "Bros",
            "Brosova",
            "Brosz",
            "Broszova",
            "Brozek",
            "Brtan",
            "Bruna",
            "Bruncak",
            "Brunciakova",
            "Bruncko",
            "Brunclik",
            "Brunnerova",
            "Brunovsky",
            "Brutenic",
            "Bubanec",
            "Bubenik",
            "Bubniakova",
            "Bucany",
            "Bucek",
            "Buchcar",
            "Buchnicek",
            "Buchova",
            "Buchta",
            "Bucik",
            "Bucka",
            "Bucko",
            "Buday",
            "Budos",
            "Budvesel",
            "Budzel",
            "Bugan",
            "Bujna",
            "Buktova",
            "Bukva",
            "Bulej",
            "Bulik",
            "Bulka",
            "Bulla",
            "Bullova",
            "Buma",
            "Buocikova",
            "Burak",
            "Burda",
            "Burdiak",
            "Burgan",
            "Bursa",
            "Busfy",
            "Buvalova",
            "Buzalka",
            "Buzas",
            "Buzna",
            "Bymova",
            "Bystrianska",
            "Bystricky",
            "Cabadaj",
            "Caban",
            "Cabanikova",
            "Cabanova",
            "Cacana",
            "Cagan",
            "Cajka",
            "Cajkovic",
            "Caky",
            "Camfrla",
            "Canady",
            "Caniga",
            "Canigova",
            "Canova",
            "Capekova",
            "Capka",
            "Capko",
            "Capkova",
            "Caprnka",
            "Carny",
            "Carvaga",
            "Casano",
            "Caso",
            "Castkova",
            "Catlos",
            "Caucik",
            "Cavoj",
            "Cavojcova",
            "Cavojsky",
            "Cebecauer",
            "Cech",
            "Cecko",
            "Ceckova",
            "Cegledy",
            "Cejka",
            "Celesova",
            "Celko",
            "Celkova",
            "Cellar",
            "Cemes",
            "Cendulova",
            "Cenek",
            "Cengel",
            "Censcak",
            "Cepcani",
            "Cepe",
            "Cepek",
            "Cepko",
            "Ceresna",
            "Cermak",
            "Cermakova",
            "Cernacek",
            "Cernak",
            "Cernanova",
            "Cernansky",
            "Cernekova",
            "Cerniga",
            "Cerny",
            "Certikova",
            "Cerven",
            "Cervena",
            "Cervenak",
            "Cervenanska",
            "Cervenansky",
            "Cervencik",
            "Cervenec",
            "Cerveny",
            "Cesnek",
            "Ceterova",
            "Chabada",
            "Chabadova",
            "Chadima",
            "Chamaj",
            "Chamajova",
            "Chano",
            "Charvat",
            "Chlapecka",
            "Chlebik",
            "Chlebnican",
            "Chlepko",
            "Chlpek",
            "Chmela",
            "Chmelik",
            "Chmulik",
            "Chobot",
            "Chochlik",
            "Chocholacek",
            "Chocholackova",
            "Chochula",
            "Chocina",
            "Chodelka",
            "Choleva",
            "Chomova",
            "Chorvat",
            "Chovan",
            "Chovancak",
            "Chovancik",
            "Chovancova",
            "Chovanec",
            "Chovanova",
            "Chrastina",
            "Chrenak",
            "Chrenko",
            "Chrenkova",
            "Chreno",
            "Chromek",
            "Chromicikova",
            "Chu",
            "Chudoba",
            "Chudy",
            "Chutka",
            "Chvastek",
            "Chymo",
            "Ciampor",
            "Cibenka",
            "Cibula",
            "Cibulas",
            "Cibulka",
            "Cibulova",
            "Cicmanec",
            "Ciel",
            "Ciernik",
            "Cierny",
            "Ciesar",
            "Ciffery",
            "Cigan",
            "Ciganik",
            "Cigas",
            "Ciger",
            "Cigerova",
            "Cihanova",
            "Cikkel",
            "Ciljak",
            "Cillik",
            "Cimbak",
            "Cimerakova",
            "Cimra",
            "Cimrakova",
            "Cingel",
            "Cinko",
            "Cipak",
            "Ciprich",
            "Cisarik",
            "Cisarikova",
            "Cizmar",
            "Cizmik",
            "Cmarada",
            "Cmol",
            "Cogr",
            "Comorek",
            "Conto",
            "Copak",
            "Corba",
            "Corej",
            "Corny",
            "Csajkovszka",
            "Csanyiova",
            "Csizmadia",
            "Csomos",
            "Csuhajova",
            "Cubon",
            "Cuchran",
            "Culak",
            "Culen",
            "Cunderlik",
            "Cuninga",
            "Cuntala",
            "Cupka",
            "Curilla",
            "Curjak",
            "Cut",
            "Cutka",
            "Cuvalova",
            "Cvacho",
            "Cvan",
            "Cvaniga",
            "Cvespr",
            "Cvik",
            "Cvirik",
            "Czastek",
            "Czeczotka",
            "Czetner",
            "Czippel",
            "Dacho",
            "Dadaj",
            "Dadakova",
            "Dado",
            "Dalog",
            "Daniel",
            "Danisek",
            "Daniska",
            "Daniskova",
            "Danisova",
            "Danko",
            "Dano",
            "Darfas",
            "Darida",
            "Darivcak",
            "Daubner",
            "David",
            "Davidik",
            "Debnar",
            "Debrovska",
            "Dechtarova",
            "Decky",
            "Dedak",
            "Dekretova",
            "Dekys",
            "Demcak",
            "Demeterova",
            "Demitrovova",
            "Dendis",
            "Denko",
            "Depes",
            "Dian",
            "Dianiska",
            "Dibak",
            "Dietl",
            "Dinzik",
            "Dioszeghy",
            "Diveky",
            "Divinsky",
            "Dlhos",
            "Dlugopolsky",
            "Dlugos",
            "Dlugosova",
            "Dluhy",
            "Dobes",
            "Dobias",
            "Dobis",
            "Doblej",
            "Dobos",
            "Dobrotka",
            "Dobrovoda",
            "Dobrovodsky",
            "Dobrovolska",
            "Dobrucka",
            "Docarova",
            "Dodek",
            "Dodok",
            "Dokoupil",
            "Dolezal",
            "Dolezalova",
            "Dolezelova",
            "Dolinaj",
            "Dolinajec",
            "Dolnik",
            "Dolnikova",
            "Dolny",
            "Donat",
            "Dono",
            "Donocik",
            "Donovalova",
            "Dora",
            "Dorcik",
            "Dorusa",
            "Dosa",
            "Dostal",
            "Doubravsky",
            "Doucha",
            "Dovjak",
            "Dragula",
            "Drestova",
            "Drevenak",
            "Drgan",
            "Drgon",
            "Drgonova",
            "Drha",
            "Drinka",
            "Drkos",
            "Drliciakova",
            "Drnec",
            "Drobec",
            "Drobul",
            "Drotarova",
            "Drozd",
            "Drozdy",
            "Drugac",
            "Drugaj",
            "Drzik",
            "Dubec",
            "Dubekova",
            "Duben",
            "Dubiel",
            "Dubovec",
            "Dubovsky",
            "Dubravka",
            "Dubsky",
            "Duc Ngo",
            "Duchonova",
            "Duchyna",
            "Duda",
            "Dudas",
            "Duffala",
            "Duga",
            "Dugas",
            "Duk",
            "Dukat",
            "Dulikova",
            "Dulovicova",
            "Dunajsky",
            "Duncko",
            "Dunik",
            "Dupac",
            "Dupcak",
            "Dupkala",
            "Dura",
            "Duracik",
            "Duraj",
            "Duran",
            "Durana",
            "Durcak",
            "Durcan",
            "Durcansky",
            "Durcek",
            "Durcik",
            "Durco",
            "Durcova",
            "Durdikova",
            "Durdinova",
            "Durec",
            "Durech",
            "Durfina",
            "Durian",
            "Durica",
            "Duricek",
            "Duricova",
            "Duriga",
            "Durina",
            "Durindak",
            "Durinik",
            "Durinikova",
            "Duris",
            "Durisova",
            "Durkac",
            "Durkacova",
            "Durkot",
            "Durkova",
            "Durkovic",
            "Duronova",
            "Duroskova",
            "Durovec",
            "Durovic",
            "Dusa",
            "Dusicka",
            "Dusik",
            "Dutka",
            "Dvorak",
            "Dvorakova",
            "Dvorsky",
            "Dzacovska",
            "Dzavan",
            "Dzetkulic",
            "Dzimko",
            "Dzivak",
            "Dzur",
            "Dzurek",
            "Dzurova",
            "Ecker",
            "Egrecka",
            "Elias",
            "Elischer",
            "Elizeus",
            "Enders",
            "Englart",
            "Englartova",
            "Ertel",
            "Ertl",
            "Espandr",
            "Estok",
            "Etrich",
            "Fabik",
            "Fabo",
            "Fabrik",
            "Fabry",
            "Fabsikova",
            "Fagan",
            "Faith",
            "Faix",
            "Fajgl",
            "Fajkus",
            "Fajna",
            "Falasta",
            "Falat",
            "Falatkova",
            "Fapso",
            "Farkas",
            "Farkasovsky",
            "Farko",
            "Fasang",
            "Fazik",
            "Fedorcakova",
            "Fedorco",
            "Fehervari",
            "Feja",
            "Fejes",
            "Fekete",
            "Fekiac",
            "Fekula",
            "Feran",
            "Ferdus",
            "Ferenc",
            "Ferencik",
            "Ferianc",
            "Ferianec",
            "Ferletjak",
            "Fetkova",
            "Fiacanova",
            "Fiala",
            "Fiam",
            "Fidrikova",
            "Figlar",
            "Filip",
            "Filipkova",
            "Fillnerova",
            "Fillo",
            "Filo",
            "Filova",
            "Fitosova",
            "Flejberk",
            "Florek",
            "Florian",
            "Florianova",
            "Florkova",
            "Florkovic",
            "Fodor",
            "Fojtik",
            "Fojtikova",
            "Foltan",
            "Foltyn",
            "Formanek",
            "Foukal",
            "Frajka",
            "Franc",
            "Francek",
            "Francekova",
            "Franek",
            "Frankova",
            "Frano",
            "Frenova",
            "Fric",
            "Fricova",
            "Fridrich",
            "Frieb",
            "Friedrichova",
            "Frivaldsky",
            "Frkan",
            "Frlicka",
            "Frniak",
            "Frolo",
            "Frolova",
            "Fronc",
            "Fryza",
            "Ftorkova",
            "Fucelova",
            "Fuchs",
            "Fuchsberger",
            "Fukas",
            "Fulajtar",
            "Fulek",
            "Fullajtar",
            "Fulop",
            "Fundarek",
            "Funtik",
            "Furdek",
            "Furielova",
            "Furik",
            "Furikova",
            "Furinda",
            "Furjel",
            "Furtak",
            "Furuglyas",
            "Fuska",
            "Gabco",
            "Gabor",
            "Gabos",
            "Gabrik",
            "Gabris",
            "Gabrisova",
            "Gacik",
            "Gahura",
            "Gaisl",
            "Gajanec",
            "Gajdiciar",
            "Gajdos",
            "Gajdosech",
            "Gajdosik",
            "Gajdosikova",
            "Gajdosova",
            "Gal",
            "Gala",
            "Galajda",
            "Galan",
            "Galbavy",
            "Galcek",
            "Galia",
            "Galik",
            "Galiovsky",
            "Galis",
            "Galkova",
            "Galla",
            "Gallik",
            "Gallova",
            "Gallovic",
            "Gally",
            "Galo",
            "Galovicova",
            "Galuszkova",
            "Gambos",
            "Gancarcik",
            "Gancarcikova",
            "Gano",
            "Ganobcik",
            "Garaj",
            "Garan",
            "Gardelka",
            "Gardlik",
            "Gartner",
            "Gasinec",
            "Gasparik",
            "Gasparovic",
            "Gasparovicova",
            "Gasper",
            "Gaspierik",
            "Gasso",
            "Gatial",
            "Gavalec",
            "Gavalier",
            "Gavenciak",
            "Gavuliak",
            "Gawron",
            "Gaza",
            "Gazda",
            "Gazdikova",
            "Gazmercikova",
            "Gazo",
            "Gazova",
            "Gazovciakova",
            "Gdovec",
            "Gebrlin",
            "Gecler",
            "Geczy",
            "Geisbacher",
            "Gejdos",
            "Gelusiak",
            "Genda",
            "Gensor",
            "Gera",
            "Gerbery",
            "Gerboc",
            "Gerhat",
            "Gerliczyova",
            "Gieci",
            "Gira",
            "Gladis",
            "Glemba",
            "Gloncak",
            "Gmitter",
            "Gmuca",
            "Gocal",
            "Gocnikova",
            "Godal",
            "Godis",
            "Goga",
            "Gogola",
            "Gogora",
            "Gogova",
            "Gold",
            "Golias",
            "Golis",
            "Golska",
            "Gombalik",
            "Gomolova",
            "Gondova",
            "Gonscak",
            "Gracova",
            "Granak",
            "Grauzel",
            "Grec",
            "Grega",
            "Gregan",
            "Gregor",
            "Gregorova",
            "Gregorovic",
            "Gregus",
            "GrenGrena",
            "Grencik",
            "Gres",
            "Gresko",
            "Gresova",
            "Gressa",
            "Grestiakova",
            "Grigorov",
            "Grilus",
            "Grman",
            "Grmela",
            "Grobarcik",
            "Grofova",
            "Grolmus",
            "Grom",
            "Grondzak",
            "Grondzakova",
            "Gronerova",
            "Grossmannova",
            "Gruchala",
            "Grznar",
            "Grznarik",
            "Gubecka",
            "Gubis",
            "Gucka",
            "Gula",
            "Gulac",
            "Guldanova",
            "Guman",
            "Gunar",
            "Gunis",
            "Gunka",
            "Guoth",
            "Guran",
            "Gurican",
            "Gurnik",
            "Gurtler",
            "Gurtlerova",
            "Gustinak",
            "Gutleber",
            "Gutten",
            "Guziniakova",
            "Gyetven",
            "Gylanik",
            "Gyurov",
            "Ha Duy",
            "Haase",
            "Habalcik",
            "Habara",
            "Hablak",
            "Habrun",
            "Had",
            "Haderka",
            "Hajas",
            "Hajda",
            "Hajdu",
            "Hajduchova",
            "Hajduk",
            "Hajdukova",
            "Hajek",
            "Hajicek",
            "Hajnala",
            "Hajny",
            "Hajovska",
            "Hajovsky",
            "Hajtinger",
            "Hajtol",
            "Halac",
            "Halaj",
            "Halama",
            "Halanda",
            "Halas",
            "Halcin",
            "Haleckova",
            "Halimovicova",
            "Halko",
            "Halkova",
            "Hallo",
            "Halmo",
            "Halupka",
            "Halus",
            "Haluska",
            "Haluskova",
            "Halvon",
            "Hamada",
            "Hamerlik",
            "Hammerle",
            "Hammerstein",
            "Hamsik",
            "Hamza",
            "Hanacek",
            "Hanajik",
            "Hanak",
            "Hanakovic",
            "Hanc",
            "Hancovsky",
            "Handl",
            "Handzus",
            "Hanic",
            "Hanidziarova",
            "Hano",
            "Hanout",
            "Hanula",
            "Hanulay",
            "Hanuliak",
            "Hanulik",
            "Hanuska",
            "Hanusova",
            "Hanzel",
            "Hanzeli",
            "Hanzelka",
            "Hanzlik",
            "Hapl",
            "Harabin",
            "Harag",
            "Haragova",
            "Harakal",
            "Harant",
            "Harasta",
            "Harcek",
            "Hareznik",
            "Harich",
            "Harmata",
            "Harmatova",
            "Haronik",
            "Harsanik",
            "Harsanyi",
            "Hartl",
            "Harustiak",
            "Hasanova",
            "Haskova",
            "Hastik",
            "Hatala",
            "Hatalova",
            "Hauer",
            "Haulik",
            "Hauptvogl",
            "Hausdorfova",
            "Hausner",
            "Haverl",
            "Havjar",
            "Havlas",
            "Havlikova",
            "Hazda",
            "Hazucha",
            "Hazuchova",
            "Heblakova",
            "Heczko",
            "Hedvigova",
            "Hedvigy",
            "Heglas",
            "Heimlich",
            "Heinrich",
            "Hempel",
            "Hencova",
            "Henikova",
            "Hepner",
            "Herceg",
            "Hercegh",
            "Hercek",
            "Herchel",
            "Herchl",
            "Hercko",
            "Herian",
            "Heribanova",
            "Herkel",
            "Herko",
            "Herman",
            "Hertelova",
            "Herudova",
            "Hianik",
            "Hikl",
            "Hince",
            "Hinke",
            "Hipik",
            "Hirtl",
            "Hlad",
            "Hladik",
            "Hladikova",
            "Hladky",
            "Hlas",
            "Hlatky",
            "Hlavac",
            "Hlavacik",
            "Hlavacova",
            "Hlavaty",
            "Hlavicka",
            "Hlincik",
            "Hlinicanova",
            "Hlinka",
            "Hlinkova",
            "Hloska",
            "Hloskova",
            "Hlosta",
            "Hlozny",
            "Hlubik",
            "Hluzakova",
            "Hnat",
            "Hnidzikova",
            "Hnojcik",
            "Hobzova",
            "Hodon",
            "Hoferica",
            "Hohr",
            "Hojer",
            "Holak",
            "Holakova",
            "Holas",
            "Holba",
            "Holbay",
            "Holdos",
            "Holec",
            "Holeczy",
            "Holes",
            "Holisova",
            "Holla",
            "Holly",
            "Holosova",
            "Holtan",
            "Holub",
            "Holubcik",
            "Holubec",
            "Holy",
            "Holzbar",
            "Homola",
            "Homolova",
            "Horak",
            "Horcickova",
            "Horna",
            "Hornak",
            "Horniak",
            "Hornicek",
            "Hornik",
            "Horsky",
            "Horvat",
            "Horvath",
            "Horvathova",
            "Hosalova",
            "Hostak",
            "Hostakova",
            "Houba",
            "Houstecky",
            "Hovancik",
            "Hrabala",
            "Hrabik",
            "Hrabos",
            "Hrabovcin",
            "Hrabovec",
            "Hrabovsky",
            "Hrabusa",
            "Hrach",
            "Hrachalova",
            "Hradecky",
            "Hradsky",
            "Hrasko",
            "Hrasna",
            "Hrcka",
            "Hrda",
            "Hrdlicka",
            "Hrdy",
            "Hreha",
            "Hrenak",
            "Hriadel",
            "Hric",
            "Hricko",
            "Hrin",
            "Hrina",
            "Hrinova",
            "Hrivnak",
            "Hrklova",
            "Hrkut",
            "Hrmo",
            "Hrnciarova",
            "Hrnko",
            "Hrobak",
            "Hromada",
            "Hromadka",
            "Hronec",
            "Hroznarova",
            "Hrtko",
            "Hruba",
            "Hrubizna",
            "Hrubjak",
            "Hrubos",
            "Hrusik",
            "Hruska",
            "Hruskova",
            "Hrusovsky",
            "Hrustincova",
            "Hrvol",
            "Hubac",
            "Hubert",
            "Hucik",
            "Hucko",
            "Hucsova",
            "Hudak",
            "Hudakova",
            "Hudcek",
            "Hudec",
            "Hudecek",
            "Hudecova",
            "Hudek",
            "Hudekova",
            "Hudik",
            "Hudziec",
            "Hudzik",
            "Hugan",
            "Hujo",
            "Hulekova",
            "Hulinova",
            "Huljak",
            "Hulla",
            "Hulman",
            "Humaj",
            "Huncakova",
            "Hunka",
            "Huraj",
            "Hurtik",
            "Hurych",
            "Husarik",
            "Husarova",
            "Huska",
            "Hutira",
            "Hutka",
            "Hutkova",
            "Hvisc",
            "Hvizdak",
            "Hvorecny",
            "Hyben",
            "Hybl",
            "Hynst",
            "Hyravy",
            "Igonda",
            "Ihnatko",
            "Ilavska",
            "Ilavsky",
            "Ilcik",
            "Illencik",
            "Imrich",
            "Imrisek",
            "Imriska",
            "Iskerkova",
            "Istenik",
            "Istok",
            "Istokovicova",
            "Istvan",
            "Ivan",
            "Ivancik",
            "Ivancova",
            "Ivanic",
            "Ivanics",
            "Ivanko",
            "Ivaska",
            "Ivaskova",
            "Ivor",
            "Izo",
            "Jablonsky",
            "Jackaninova",
            "Jacko",
            "Jackova",
            "Jackovicova",
            "Jaco",
            "Jagelka",
            "Jagrik",
            "Jakab",
            "Jakabovic",
            "Jakes",
            "Jakubcik",
            "Jakube",
            "Jakubec",
            "Jakubech",
            "Jakubek",
            "Jakubik",
            "Jakubisova",
            "Jakubov",
            "Jakubovie",
            "Jalcova",
            "Jambrichova",
            "Jamrich",
            "Janacikova",
            "Janak",
            "Jancarik",
            "Jancek",
            "Janci",
            "Janciak",
            "Jancik",
            "Jancikova",
            "Janciova",
            "Janckulik",
            "Janco",
            "Jancoska",
            "Jancovic",
            "Jancuch",
            "Jancura",
            "Jancurova",
            "Jancuska",
            "Jancuskova",
            "Jancusova",
            "Jandak",
            "Janech",
            "Janeckova",
            "Janek",
            "Janekova",
            "Jani",
            "Janic",
            "Janicek",
            "Janicekova",
            "Janicina",
            "Janickova",
            "Janicova",
            "Janiga",
            "Janigova",
            "Janik",
            "Janis",
            "Janits",
            "Jankal",
            "Jankola",
            "Jankovic",
            "Jankovsky",
            "Janku",
            "Janky",
            "Janos",
            "Janosik",
            "Janoska",
            "Janotkova",
            "Janovec",
            "Jantacka",
            "Jantek",
            "Jantosciakova",
            "Jantosik",
            "Janura",
            "Janus",
            "Januska",
            "Jany",
            "Janzo",
            "Jarabak",
            "Jarabicova",
            "Jarina",
            "Jarkovsky",
            "Jaros",
            "Jarosciak",
            "Jarosova",
            "Jasak",
            "Jascurova",
            "Jaseckova",
            "Jasenovec",
            "Jasica",
            "Jasikova",
            "Jasso",
            "Jassova",
            "Jasta",
            "Javor",
            "Javorcik",
            "Javorka",
            "Javornicka",
            "Javorska",
            "Jecim",
            "Jedinak",
            "Jedinakova",
            "Jekkel",
            "Jelenik",
            "Jelenovsky",
            "Jelinek",
            "Jemala",
            "Jendrejcakova",
            "Jendrisak",
            "Jendruch",
            "Jenej",
            "Jesenko",
            "Jesensky",
            "Jevjak",
            "Jezek",
            "Jezercak",
            "Jezik",
            "Jezikova",
            "Jilek",
            "Jirsova",
            "Jiru",
            "Jobb",
            "Jochec",
            "Johanides",
            "Jokel",
            "Jolov",
            "Jostiak",
            "Juhaniak",
            "Junasova",
            "Junosova",
            "Juramik",
            "Jurcikova",
            "Jurciova",
            "Jurco",
            "Jurecka",
            "Juric",
            "Juricek",
            "Juriga",
            "Jurik",
            "Jurikova",
            "Jurina",
            "Jurisic",
            "Jurista",
            "Juritka",
            "Jurkovic",
            "Jurosko",
            "Juskova",
            "Just",
            "Kabac",
            "Kacalka",
            "Kacenkova",
            "Kaceriak",
            "Kacerik",
            "Kacian",
            "Kacir",
            "Kacirova",
            "Kacmar",
            "Kadacik",
            "Kadak",
            "Kadarova",
            "Kadasiova",
            "Kaderka",
            "Kadia",
            "Kadlecik",
            "Kager",
            "Kahan",
            "Kahanik",
            "Kaikl",
            "Kajanova",
            "Kakos",
            "Kala",
            "Kalafut",
            "Kalavsky",
            "Kalina",
            "Kallay",
            "Kalma",
            "Kalmanova",
            "Kalnovicova",
            "Kalocova",
            "Kaman",
            "Kamas",
            "Kamenicky",
            "Kamenistak",
            "Kamensky",
            "Kamody",
            "Kamp",
            "Kampa",
            "Kanderka",
            "Kangas",
            "Kaniansky",
            "Kanicka",
            "Kanik",
            "Kanis",
            "Kanka",
            "Kanocz",
            "Kantor",
            "Kapalka",
            "Kapicak",
            "Kapitan",
            "Kapitulik",
            "Kapral",
            "Kapusnak",
            "Kapusniak",
            "Kapusta",
            "Kapustkova",
            "Kapustova",
            "Karaba",
            "Karak",
            "Karas",
            "Karasek",
            "Karch",
            "Kardos",
            "Karkusz",
            "Karpis",
            "Karpisova",
            "Karvasova",
            "Kasagranda",
            "Kasaj",
            "Kasak",
            "Kasakova",
            "Kasala",
            "Kasanicky",
            "Kasiar",
            "Kaslova",
            "Kasman",
            "Kasmanova",
            "Kaspar",
            "Kasparek",
            "Kasprak",
            "Kasprisinova",
            "Kassa",
            "Kasuba",
            "Katanik",
            "Katrenik",
            "Katrik",
            "Katuscak",
            "Kavalek",
            "Kavecky",
            "Kavka",
            "Kazarik",
            "Kazarova",
            "Kazik",
            "Kecerova",
            "Kejmar",
            "Kekeliova",
            "Kekely",
            "Kelcik",
            "Kelemen",
            "Kellner",
            "Kello",
            "Kelschova",
            "Kemenik",
            "Kenderova",
            "Kendra",
            "Keracik",
            "Kerbis",
            "Kereskeni",
            "Kern",
            "Kerpner",
            "Kery",
            "Kesely",
            "Keyzlar",
            "Kianica",
            "Kianicka",
            "Kianickova",
            "Kilianova",
            "Kilik",
            "Kincesova",
            "Kiralyova",
            "Kirschbaum",
            "Kis",
            "Kiss",
            "Kissa",
            "Kivader",
            "Klabouch",
            "Klacanova",
            "Klacko",
            "Klackova",
            "Klaudiny",
            "Klein",
            "Kleinova",
            "Kleman",
            "Klempai",
            "Klen",
            "Klenovicova",
            "Klepacova",
            "Klima",
            "Klimcakova",
            "Klimcikova",
            "Klimek",
            "Klimes",
            "Klimko",
            "Klimo",
            "Klimova",
            "Klinovsky",
            "Klizan",
            "Klotton",
            "Kluciar",
            "Kluckova",
            "Klucovsky",
            "Kluska",
            "Klusova",
            "Kluvankova",
            "Kmec",
            "Kmecova",
            "Kment",
            "Kmet",
            "Kmetova",
            "Knajbel",
            "Knapik",
            "Knapp",
            "Knaze",
            "Knazko",
            "Kneznikova",
            "Knoblich",
            "Knopova",
            "Knosko",
            "Knutelsky",
            "Kobella",
            "Koblizek",
            "Kobolka",
            "Kobrova",
            "Kochlan",
            "Kochman",
            "Kochol",
            "Koci",
            "Kocian",
            "Kocianova",
            "Kocifaj",
            "Kocifajova",
            "Kociova",
            "Kocis",
            "Kocka",
            "Kocova",
            "Kocsisova",
            "Kocurova",
            "Kocvara",
            "Kohani",
            "Kohus",
            "Kohut",
            "Kohutka",
            "Kojda",
            "Kojdjak",
            "Kolaci",
            "Kolacia",
            "Kolaja",
            "Kolarik",
            "Kolcak",
            "Kolcun",
            "Kolencik",
            "Kolesar",
            "Kolesarova",
            "Kolestik",
            "Koliba",
            "Kolibiar",
            "Kolinek",
            "Kollar",
            "Kollarik",
            "Kollarova",
            "Komacka",
            "Komada",
            "Komandera",
            "Komanderova",
            "Kominek",
            "Kominkova",
            "Komorovsky",
            "Kompan",
            "Kona",
            "Konar",
            "Konc",
            "Koncelik",
            "Koncko",
            "Koncz",
            "Konde",
            "Kondelova",
            "Kondrla",
            "Konecna",
            "Konecny",
            "Konfalova",
            "Kontelik",
            "Kontros",
            "Kontsek",
            "Konvit",
            "Kopac",
            "Kopal",
            "Kopasek",
            "Kopca",
            "Kopcansky",
            "Kopcek",
            "Kopecky",
            "Kopecna",
            "Kopera",
            "Kopernicky",
            "Kopilec",
            "Kopinec",
            "Koprda",
            "Kopun",
            "Kopunec",
            "Korbas",
            "Korbelova",
            "Korcak",
            "Korcek",
            "Korcsmaros",
            "Kordos",
            "Koren",
            "Korenciak",
            "Koricina",
            "Koristova",
            "Kormanak",
            "Kormanova",
            "Kormos",
            "Korycan",
            "Korytak",
            "Kosa",
            "Kosan",
            "Kosarek",
            "Kosc",
            "Kosco",
            "Koscova",
            "Kosek",
            "Koskar",
            "Kosmal",
            "Kosorinova",
            "Kosorinsky",
            "Kosova",
            "Kosper",
            "Kossiba",
            "Kossova",
            "Kost",
            "Kosta",
            "Kostial",
            "Kostialova",
            "Kostka",
            "Kostolna",
            "Kostolny",
            "Kostra",
            "Kostrianova",
            "Kostrna",
            "Kostros",
            "Kostur",
            "Kosturova",
            "Kosulicova",
            "Kothaj",
            "Kotillova",
            "Kotlar",
            "Kotrik",
            "Kotulasova",
            "Kotvova",
            "Koutny",
            "Kovac",
            "Kovacik",
            "Kovacikov?",
            "Kovacova",
            "Koval",
            "Kovalcik",
            "Kovalicek",
            "Kovalik",
            "Kovar",
            "Kovarcik",
            "Kovarova",
            "Koys",
            "Koza",
            "Kozacik",
            "Kozak",
            "Kozakova",
            "Kozar",
            "Kozehuba",
            "Kozel",
            "Kozikova",
            "Kozlovska",
            "Kozlovsky",
            "Kozokova",
            "Kozuch",
            "Kozusko",
            "Krafcik",
            "Krahulec",
            "Krajc",
            "Krajca",
            "Krajci",
            "Krajciova",
            "Krajcir",
            "Krajcirik",
            "Krajcirovic",
            "Krajco",
            "Krajcovic",
            "Krajnikova",
            "Krakovsky",
            "Kral",
            "Kralik",
            "Kralikova",
            "Kralova",
            "Kramar",
            "Krasula",
            "Kratky",
            "Krausko",
            "Kravarik",
            "Krbata",
            "Krc",
            "Krchnava",
            "Krchnavy",
            "Krcho",
            "Krchova",
            "Krcmarik",
            "Krcmarikova",
            "Kredatus",
            "Kremel",
            "Krempa",
            "Krempasky",
            "Krenz",
            "Krilek",
            "Kriska",
            "Kriss",
            "Krist",
            "Kristak",
            "Kristekova",
            "Kristof",
            "Kristofcak",
            "Kristoffy",
            "Kristofik",
            "Krivda",
            "Krivosek",
            "Krivulcik",
            "Krivy",
            "Kriz",
            "Krizan",
            "Krizansky",
            "Krizek",
            "Krizik",
            "Krkos",
            "Krkoska",
            "K:rmendy",
            "Krnac",
            "Krncanova",
            "Krncok",
            "Krocian",
            "Krocianova",
            "Krocity",
            "Krockova",
            "Krotki",
            "Kroupa",
            "Krpec",
            "Krpelan",
            "Krsak",
            "Krsakova",
            "Krsiak",
            "Krsiakova",
            "Krsjak",
            "Krssak",
            "Krug",
            "Krupa",
            "Krupik",
            "Krusinsky",
            "Krutosik",
            "Kruzliak",
            "Kruzlicova",
            "Kuba",
            "Kubacka",
            "Kubala",
            "Kubalik",
            "Kubalova",
            "Kuban",
            "Kubanek",
            "Kubani",
            "Kubankova",
            "Kubasak",
            "Kubasek",
            "Kubaskova",
            "Kubek",
            "Kubenko",
            "Kubica",
            "Kubicek",
            "Kubickova",
            "Kubik",
            "Kubikova",
            "Kubina",
            "Kubincanek",
            "Kubinciakova",
            "Kubis",
            "Kubita",
            "Kubof",
            "Kubov",
            "Kubova",
            "Kubovcik",
            "Kuca",
            "Kucak",
            "Kucan",
            "Kucecka",
            "Kucera",
            "Kucerova",
            "Kuchar",
            "Kucharik",
            "Kucharovic",
            "Kuchcakova",
            "Kuchta",
            "Kuchtova",
            "Kuchyna",
            "Kuchynar",
            "Kuciak",
            "Kucian",
            "Kucko",
            "Kudlaty",
            "Kudlicka",
            "Kufa",
            "Kufner",
            "Kukuca",
            "Kukucka",
            "Kukura",
            "Kulhavy",
            "Kulich",
            "Kulik",
            "Kulikova",
            "Kulina",
            "Kuliska",
            "Kuliskova",
            "Kuljovska",
            "Kuljovsky",
            "Kulka",
            "Kulla",
            "Kuna",
            "Kunaj",
            "Kunak",
            "Kundrik",
            "Kunetka",
            "Kunhart",
            "Kunsch",
            "Kupcok",
            "Kupculakova",
            "Kupec",
            "Kupka",
            "Kupsky",
            "Kuran",
            "Kurcik",
            "Kurcin",
            "Kurcina",
            "Kurdaj",
            "Kurek",
            "Kurekova",
            "Kurhajcova",
            "Kuric",
            "Kuricova",
            "Kurillova",
            "Kurimsky",
            "Kuris"
    );

    private static List<String> KATASTRALNE_UZEMIA = Arrays.asList(
            "Klokocov",
            "Dolna Tizina",
            "Zuberec",
            "Stara Bystrica",
            "Vysoka nad Uhom",
            "Povazska Tepla",
            "Nove Zamky",
            "Velka Maca",
            "Liptovske Revuce",
            "Kremnicke Bane",
            "Predajna",
            "Liptovska Tepla",
            "Necpaly",
            "Trebisov",
            "Vahovce",
            "Velke Lovce",
            "Zabokreky nad Nitrou",
            "Mutne",
            "Velka Trna",
            "Michalovce",
            "Horna Streda",
            "Klatova Nova Ves",
            "Liptovska Luzna",
            "Suja - Rajec",
            "Povazska Bystrica",
            "Chtelnica",
            "Adamov",
            "Lucky",
            "Kunovice",
            "Cadca",
            "Dolny Kubin",
            "Gbelce",
            "Malcov",
            "Pribor",
            "Poluvsie",
            "Bystricany",
            "Praznovce",
            "Radola",
            "Plevnik",
            "Tisovec",
            "Sihelne",
            "Spisske Podhradie",
            "Zavazna Poruba",
            "Lubica",
            "Kalna Nad Hronom",
            "Biely Potok",
            "Vycapy - Opatovce",
            "Tabor",
            "Pelhrimov",
            "Sered",
            "Zemplinske Hamre",
            "Dlhe Pole",
            "Lazany",
            "Vlkanova",
            "Batizovce",
            "Mohelnice",
            "Pata",
            "Klacany",
            "Palarikovo",
            "Svedernik",
            "Pobedim",
            "Hontianske Nemce",
            "Velke Kostolany",
            "Medzilaborce",
            "Udavske",
            "Zilina",
            "Otrokovice",
            "Zilina 7",
            "Bratislava",
            "Nova Dubnica",
            "Banska Stiavnica",
            "Banska Stiavnica",
            "Turzovka",
            "Bzenec",
            "Vrable",
            "Zaskov",
            "Spisska Nova Ves",
            "Veseli nad Moravou",
            "Krivan",
            "Kolarovice",
            "Velke Uherce",
            "Rabcice",
            "Ostrovany",
            "Levoca",
            "Belusa",
            "Divina",
            "Kvacany",
            "Horna Stubna",
            "Frydek Mistek",
            "Lazy pod Makytou",
            "Zelovce",
            "Zlin",
            "Teplicka nad Vahom",
            "Prakovce",
            "Smrecany",
            "Liptovsky Mikulas",
            "Lubisa",
            "Namestovo Brehy",
            "Jablonica",
            "Brvniste 541",
            "Cavoj",
            "Radvan",
            "Hanusovce nad Toplou",
            "Dezerice",
            "Zlate Klasy",
            "Tvrdosin",
            "Huncovce",
            "Velky Kliz",
            "Michal nad Zitavou",
            "Praha - Prosek 9",
            "Malacky",
            "Nove Zamky",
            "Giraltovce",
            "Volary",
            "Secovce",
            "Trnovec nad Vahom",
            "Dolny Stal",
            "Hlinik nad Hronom",
            "Presov - Lubotice",
            "Predmier",
            "Brezovka",
            "Chorvatsky Grob",
            "Chynorany",
            "Salgovce",
            "Stanca-Upor",
            "Raslavice",
            "Vysny Kubin",
            "Hradok nad Vahom",
            "Valasske Mezirici",
            "Helpa",
            "Pichne",
            "Bratislava",
            "Nivnice",
            "Udica",
            "Kosice",
            "Brodske",
            "Sliac",
            "Radslavice",
            "Usti nad Orlici",
            "Senica",
            "Dlha Ves",
            "Rosina",
            "Podbranc",
            "Smizany",
            "Selce",
            "Kunova Teplica",
            "Velke Slemence",
            "Kokava nad Rimavicou",
            "Jazernica",
            "Bytca-Hlboke",
            "Valaska",
            "Kralovsky Chlmec",
            "Stankovany",
            "Podrecany",
            "Moravsky Beroun",
            "Medzany-Velky Saris",
            "Martin - Priekopa",
            "Hermanovce nad Toplo",
            "Skacany",
            "Bratislava",
            "Klusov",
            "Koprivnice",
            "Spisska Stara Ves",
            "Borsky Mikulas",
            "Obyce",
            "Slavosovce",
            "Zlin",
            "Hvozdnica",
            "Banovece nad Bebravo",
            "Solosnica",
            "Vrutky - Lipovec",
            "Cernik",
            "Drahovce",
            "Jakubany",
            "Podhorod",
            "Povazska Bystrica",
            "Lednicke Rovne",
            "Nove Mesto nad Vahom",
            "Istebne",
            "Samorin",
            "Oravske Vesele",
            "Ton",
            "Trnava",
            "Kotesova",
            "Krupina",
            "Velka Lomnica",
            "Tornala",
            "Zarnovica",
            "Turany nad Ondavou",
            "Dobra Niva",
            "Jasenica",
            "Kamenica nad Hronom",
            "Mlynky",
            "Michalovce",
            "Sebedrazie",
            "Banska Bystrica",
            "Bratislava",
            "Nova Bana",
            "Krusetnica",
            "Banov",
            "Bratislava 3",
            "Prerov",
            "Praha",
            "Horny Hricov",
            "Melnik",
            "Vychodna",
            "Poprad",
            "Lutila",
            "Klin",
            "Luzianky",
            "Nove Zamky",
            "Sliac",
            "Staskov",
            "Praha 2",
            "Vysny Hruskov",
            "Nitrica",
            "Dolne Srnie",
            "Nove Zamky",
            "Dolny Hricov",
            "Stropkov",
            "Krompachy",
            "Caka",
            "Poprad - Matejovce",
            "Trencianska Tepla",
            "Velky Krtis",
            "Zemberovce",
            "Povazany",
            "Svinna",
            "Leopoldov",
            "Zborov nad Bystricou",
            "Medzilaborce",
            "Lukavica",
            "Strazske",
            "Hybe",
            "Spisska Teplica",
            "Rapovce",
            "Bratislava 7",
            "Podivin",
            "Slovenska Lupca",
            "Zbudske Dlhe",
            "Dolni Paseky",
            "Nizny Hrusov",
            "Kojsov",
            "Zemberovce",
            "Skalica",
            "Drietoma",
            "Bystricka",
            "Letanovce",
            "Pecky",
            "Bobot",
            "Bela nad Cirochou",
            "Sturovo",
            "Zelielzovce",
            "Bratislava",
            "Kalinovo",
            "Nitra-Klokocian",
            "Medzibrod",
            "Kosecke Podhradie",
            "Lucenec",
            "Prerov",
            "Dolni Lomna",
            "Unin",
            "Ludanice",
            "Rohoznik",
            "Streda nad Bodrogom",
            "Berlin",
            "Popudinske Mocidlany",
            "Ceske Budejovice",
            "Jarovnice",
            "Frydek-Mistek",
            "Sebestanova 169",
            "Martin",
            "Sasinkovo",
            "Opatovce nad Nitrou",
            "Velke Nemnice",
            "Kamenna Poruba",
            "Stepanov",
            "Trstena",
            "Bobrovec",
            "Dravce",
            "Kysucke Nove Mesto",
            "Pezinok",
            "Turany",
            "Raztocno",
            "Horne Hamre",
            "Cierna nad Tisou",
            "Vrbove",
            "Myjava",
            "Domaniza",
            "Dojc",
            "Tatranska Strba",
            "Nove Zamky",
            "Novot",
            "Knezeves",
            "Pribovce",
            "Liptovska Osada",
            "Sisov",
            "Banov",
            "Topolovka",
            "Kapusany pri Presove",
            "Jacovce",
            "Hankovce",
            "Tatranska Lomnica",
            "Kosice 3",
            "Lucatin",
            "Branovo",
            "Kosice 12",
            "Tekovska Breznica",
            "Ruzomberok",
            "Vysny Zipov",
            "Bratislava",
            "Koniarovce",
            "Bosaca",
            "Detvianska Huta",
            "Horna Suca",
            "Komoca",
            "Bela - Dulice",
            "Trencin",
            "Trencin",
            "Vranov nad Toplou",
            "Bratislava",
            "Ostratice",
            "Raznany",
            "Zariecie",
            "Hulin",
            "Bratislava",
            "Cerenany",
            "Gelnica",
            "Melcice-Lieskove",
            "Dobsina",
            "Fackov",
            "Bzenov",
            "Nove Zamky",
            "Chocholna-Velcice",
            "Solcany",
            "Binovce",
            "Hlinik nad Hronom",
            "Frydek-Mistek",
            "Matiasovce",
            "Sala",
            "Skalite",
            "Zdiar",
            "Cadca",
            "Kos",
            "Sobrance",
            "Strecno",
            "Brezno",
            "Neded",
            "Nizna",
            "Mula",
            "Diviaky nad Nitricou",
            "Hronsky Benadik 210",
            "Ladzany",
            "Nova Lubovna",
            "Komarno",
            "Zvolenska Slatina",
            "Korna",
            "Papradno",
            "Sabinov",
            "Krajne",
            "Soporna",
            "Pcoline",
            "Brno",
            "Rimavska Sobota",
            "Oravska Jasenica",
            "Ostrava-1",
            "Liestany",
            "Trinec 5",
            "Stola",
            "Trebon",
            "Trstena",
            "Vechec",
            "Dunajska Streda",
            "Bratislava III.",
            "Prestavlky",
            "Trencianske Jastrabi",
            "Bludov",
            "Moravske Branice",
            "Spissky Stiavnik",
            "Spisske Bystre",
            "Lovca",
            "Stiavnicke Bane",
            "Benesov",
            "Surany",
            "Cierny Balog",
            "Ceska Trebova",
            "Svaty Jur",
            "Galanta",
            "Vyskov",
            "Sahy",
            "Viglas",
            "Trnava",
            "Slatina n/B",
            "Pohorela",
            "Kralovany",
            "Kostany nad Turcom",
            "Nova Ves nad Zitavou",
            "Studenka",
            "Vrbovka",
            "Vranou nad Toplou",
            "Pozdisovce",
            "Valaska Bela",
            "Tabor",
            "Ceske Brezovo",
            "Chlmec",
            "Liptovsky Mikulas",
            "Turcians. Stiavnicka",
            "Unicov",
            "okr.Velky Krtis",
            "Kosice",
            "Siroke",
            "Slatinske Lazy",
            "Baska-Kuncicky",
            "Zborov",
            "Nachod",
            "Kralupy nad Vltavou",
            "Valaska Dubova",
            "Kuzmice-Slivnik",
            "Svidnik",
            "Travnica",
            "Hnusta",
            "Strakonice",
            "Vavrisovo",
            "Holic",
            "Koseca",
            "Kysucky Lieskovec",
            "Sered",
            "Zakamenne",
            "Zvoncin",
            "Gbelany",
            "Detva",
            "Kovacova",
            "Visnove",
            "Svitavy",
            "Litvinov 6",
            "Skalica",
            "Sumperk",
            "Detva",
            "Vysoka nad Kysucou",
            "Casta",
            "Tuchyna",
            "Krpelany",
            "Nove Zamky",
            "Palin",
            "Vyhne",
            "Bratislava - stare m",
            "Revuca",
            "Kurima",
            "Spisska Bela",
            "Olomouc",
            "Spacince-Trnava",
            "Zubrohlava",
            "Sturovo",
            "Klacno",
            "Bzovik",
            "Litvinov",
            "Visnove",
            "Oravska Lesna",
            "Horna Kralova",
            "Rejdova",
            "Vsetin",
            "Ruzomberok",
            "Hozelec",
            "Uherske Hradiste",
            "Boskovice",
            "Velka Lesna",
            "Krupina",
            "Habura",
            "Usti nad Labem",
            "Sternberk",
            "Beharovce",
            "Kyjov",
            "Bratislava",
            "Skalka nad Vahom",
            "Hurbanovo",
            "Cabaj - Capor",
            "Nadlice",
            "Prasice",
            "Rajecka Lesna",
            "Nove Sady",
            "Jarok",
            "Hradek ve Slezsku",
            "Michalova",
            "Valasske Mezirici",
            "Brezova pod Bradlom",
            "Galanta",
            "Usti nad Labem",
            "Patrovec",
            "Litava",
            "Farna",
            "Hranice na Morave",
            "Brestovany",
            "Hodonin",
            "Nalepkovo",
            "Krusovce",
            "Moravsky Svaty Jan",
            "Sladkovicovo",
            "Hul",
            "Brno",
            "Trnava",
            "Hlohovec",
            "Trencin",
            "Ilava",
            "Bratislava",
            "Pezinok",
            "Nitra",
            "Levice",
            "Rajec",
            "Plzen",
            "Banska Bystrica",
            "Zvolen",
            "Presov",
            "Poprad",
            "Kosice",
            "Michalovce",
            "Bardejov",
            "Martin",
            "Ruzomberok",
            "Lietavska Lucka",
            "Diakovce",
            "Kendice",
            "Nova Bystrica",
            "Ilava",
            "Budatinska Lehota",
            "Vazec",
            "Vyskov",
            "Zemianske Kostolany",
            "Radosina",
            "Zilina",
            "Lubochna",
            "Budkovce",
            "Dovalovo",
            "Lehota pod Vtacnikom",
            "Svrcinovec",
            "Cecejovce",
            "Petrovany",
            "Ziar nad Hronom",
            "Velehrad",
            "Ruban",
            "Uherske Hradiste",
            "Bratislava",
            "Banska Bela",
            "Nemsova",
            "Pochabany-Velke Host",
            "Lucivna",
            "Lubela",
            "Hrachovo",
            "Dolne Vestenice",
            "Pribeta",
            "Zatec",
            "Diviacka Nova Ves",
            "Zilina",
            "Zilina",
            "Zilina",
            "Liptovsky Hradok",
            "Zvolen",
            "Chrenovec",
            "Podbrezova",
            "Nove Zamky",
            "Humenne",
            "Partizanske",
            "Martin",
            "Sliace",
            "Tesarske Mlynany 269",
            "Kanianka",
            "Roznava",
            "Velke Ripnany",
            "Kezmarok",
            "Potor",
            "Hniezdne",
            "Zakopcie",
            "Kosice - mestska cas",
            "Poltar",
            "Velicna",
            "Castkovce",
            "Moravany nad Vahom",
            "Bystricka",
            "Senica nad Myjavou",
            "Trinec",
            "Trencin 8",
            "Zlate Moravce",
            "Ocova",
            "Zilina-Visnove",
            "Hradiste",
            "Bratislava 4",
            "Prasnik 261",
            "Novaky",
            "Dulov  - Pruske",
            "Ratnovce",
            "Nabrezie",
            "Dubnica  nad Vahom",
            "Martin 8",
            "Chmelnica",
            "Nitra 11",
            "Levice",
            "Hrinova",
            "Pribylina",
            "Velke Kapusany",
            "Utekac",
            "Lipova",
            "Luka",
            "Hrustin",
            "Bratislava I",
            "Zelec",
            "Kladno",
            "Rakovec nad Ondavou",
            "Kosice 11",
            "Svaty Kriz",
            "Mernik",
            "Horna Ves",
            "Pecovska Nova Ves",
            "Ipelsky Sokolec",
            "Aleksince",
            "Slovenske Pravno",
            "Teply Vrch",
            "Rovnany",
            "Handlova",
            "Slazany",
            "Podvysoka",
            "Most",
            "Velke Ucany",
            "Karlovy Vary",
            "Dohnany",
            "Rakova",
            " Sala 5",
            "Ruzomberok-Cernova",
            "Lietava",
            "Zakarovce",
            "Trakovice",
            "Sklene",
            "Banovce nad Bebravou",
            "Bobrov",
            "Nitra 5",
            "Malinec",
            "Cadca",
            "Sala",
            "Frickovce",
            "Liptovska Sielnica",
            "Strecno",
            "Malinova",
            "Vranov nad Toplou",
            "Nedozery-Brezany",
            "Sedliska",
            "Dolny Kubin",
            "Bitarova-Zavodie",
            "Makov",
            "Horne Semerovce",
            "Terchova",
            "Ladce",
            "Cervenik",
            "Klenovec",
            "Podolinec",
            "Brezovicka",
            "Jelsava",
            "Nitrianske Pravno",
            "Hronovce",
            "Sklabina",
            "Zablatie",
            "Bratislava",
            "Kuty",
            "Vidina",
            "Boleraz",
            "Likava",
            "Hlucin",
            "Piesrany",
            "Zabnica",
            "Basovce",
            "Krnov",
            "Senohrad",
            "Sklene Teplice",
            "Poruba-Lazany",
            "Komarno",
            "Zilina",
            "Sala 5",
            "Kutna Hora",
            "Gbely",
            "Presov 8",
            "Brodno",
            "Senec",
            "Hradec Kralove",
            "Vrbov",
            "Chankonce",
            "Dolny Lieskov",
            "Cadca",
            "Jindrichov",
            "Kysucky Lieskovec",
            "Ludrova",
            "Bratislava",
            "Ziar nad Hronom",
            "Kmetovo",
            "Budatin - Zilina",
            "Banska Bystrica",
            "Martin",
            "Branky",
            "Cerveny Klastor",
            "Velka Dolina",
            "Vlachovo",
            "Trencianske Teplice",
            "Krakovany",
            "Dolny Kubin",
            "Handlova",
            "Tvrdosin",
            "Lopej",
            "Havirov-Mesto",
            "Neslusa",
            "Bela",
            "Kunerad 192",
            "Trebic",
            "Podolie",
            "Poprad-Tatr.Kotlina",
            "Nacina Ves",
            "Vely Krtis",
            "Hronske Klacany",
            "Turcianske Teplice",
            "Pitelova-Trnava Hora",
            "Ostrava 3",
            "Lutila",
            "Ilava-Klobusice",
            "Zilina",
            "Turcek",
            "Bzince pod Javorinou",
            "Presov 5",
            "Prievidza",
            "Partizanske",
            "Velke Rovne",
            "Trencianska Turna",
            "Simonovany",
            "Bratislava",
            "Zazriva",
            "Klace",
            "Horka",
            "Ochodnica",
            "Levice",
            "Liptovsky Jan",
            "Bratislava",
            "Svinov",
            "Bojna",
            "Hendrichovce",
            "Zlatniky",
            "Turie",
            "Liptovsky Mikulas 4",
            "Kordiky",
            "Zlate Moravce",
            "Nove Zamky",
            "Krasno nad Kysucou",
            "Spisska Nova Ves",
            "Jelenec",
            "Pruzina",
            "Dacice",
            "Lipany",
            "Rudnik",
            "Trencin 5",
            "Breza",
            "Zabreh na Morave",
            "Liptovsky Ondrej",
            "Podkonice",
            "Ostrava 1",
            "Kojetin",
            "Tvrdosovce",
            "Semerovo",
            "Louka",
            "Bodina-Precin",
            "Slovenske Darmoty",
            "Dubove",
            "Ostrava",
            "Michajlov-Ubla",
            "Cakanovce",
            "Tekovske Luzany",
            "Sulov",
            "Mosovce",
            "Uhrovec",
            "Cierne",
            "Sarisske Dravce",
            "Rohov",
            "Olomouc",
            "Oravsky Biely Potok",
            "Dubrava",
            "Sarisske Bohdanovce",
            "Pardubice",
            "Kamenec pod Vtacniko",
            "Partizanska Lupca",
            "Trhoviste",
            "Bosany",
            "Myjava",
            "Nimnica",
            "Ziar Nad Hronom",
            "Velky Meder",
            "Jasenie",
            "Cabradsky Vrbovok",
            "Krompachy",
            "Vranov",
            "Nemce",
            "Velke Zaluzie",
            "Lovcica-Trubin",
            "Lucenec",
            "Pliesovce",
            "Borovce",
            "Kaluza",
            "Komjatice",
            "Petrovice",
            "Krasnany",
            "Dolny Vadicov",
            "Batorove Kosihy",
            "Chvalec",
            "Nemecka",
            "Albrechtice",
            "Nova Bosaca",
            "Cajkov",
            "Kluknava",
            "Bucany",
            "Velka Mana",
            "Vysna Pisana",
            "Krasno 170",
            "Louny",
            "Tapesovo",
            "Jelsovce",
            "Nitra 12",
            "Oslany",
            "Zilina",
            "Krasno nad Kysucou",
            "Hlohovec",
            "Dlha nad Oravou",
            "Drazkovce",
            "Trencin",
            "Trencianske Stankovc",
            "Kamenne Kosihy",
            "Puchov",
            "Stara Tura",
            "Bracovce",
            "Stranavy",
            "Trnava",
            "Ladomirova",
            "Lenartovce",
            "Bolesov",
            "Liskova",
            "Jaklovce",
            "Povina",
            "Strba",
            "Bardejov",
            "Prievidza",
            "Ruzomberok-Rybarpole",
            "Zvolen",
            "Partizanske",
            "Dolna Suca",
            "Tlmace",
            "Oravska Podhora"
            );


}
